name: Release Actions

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ github.event.inputs.version || github.ref_name }}

      - name: Update major version tag
        run: |
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          git tag -fa $MAJOR -m "Update $MAJOR tag to $VERSION"
          git push origin $MAJOR --force