name: Release Actions

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Update major version tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Get the version
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          echo "Version: $VERSION"
          
          # Extract major version (remove 'v' prefix if present)
          MAJOR=$(echo $VERSION | sed 's/^v//' | cut -d. -f1)
          MAJOR_TAG="v$MAJOR"
          echo "Major tag: $MAJOR_TAG"
          
          # Create/update the major version tag
          git tag -fa $MAJOR_TAG -m "Update $MAJOR_TAG tag to $VERSION"
          
          # Push the tag
          git push origin $MAJOR_TAG --force
